### ISSUE TITLE
Provide apk please.

### ISSUE THREAD

**Issue by vikrant123pundir** [ypid/ComplexAlarm#1]
I know it's an 8 year old project, but can you please provide me the apk of this so that i can run this of Android.
I don't even know that whether it was built for Android or not. But it will solve a great problem of mine if it really is for Android.
In releases, I can't find any apk. Is there really any?
I am not a techie guy so don't know how to compile project. Can it be compiled by Android studio btw.

**Comment by ypid** [comment]
Did you read https://github.com/ypid/ComplexAlarm#state-of-the-application?
